name: CI Pipeline
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0
          mongodb-username: nextcrm
          mongodb-password: nextcrm
          mongodb-db: nextcrm

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit Tests
        run: npx vitest run

      - name: Run Lint
        run: pnpm run lint
        continue-on-error: true # Warning only for now

      - name: Prisma Schema Validate
        uses: elijaholmos/prisma-schema-validate@v1.0.0
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CMS_DATABASE_URL: ${{ secrets.CMS_DATABASE_URL }}
          ENCRYPTION_KEY: ${{ secrets.API_KEY_ENCRYPTION_KEY }}

      - name: Prisma Generate and Push
        run: |
          npx prisma generate
          npx prisma db push
          npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CMS_DATABASE_URL: ${{ secrets.CMS_DATABASE_URL }}
          ENCRYPTION_KEY: ${{ secrets.API_KEY_ENCRYPTION_KEY }}
