# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: pnpm install, build, and test
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          API_KEY_ENCRYPTION_KEY: ${{ secrets.API_KEY_ENCRYPTION_KEY }}
        run: |
          pnpm install
          npx prisma generate
          pnpm run build
          pnpm run test

      - name: Prepare standalone build
        run: |
          mkdir -p .next/standalone/.next/static
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static
          rm -rf .next/standalone/node_modules/styled-jsx
          cp -rL node_modules/styled-jsx .next/standalone/node_modules/
          rm -rf .next/standalone/node_modules/@swc
          cp -rL node_modules/@swc .next/standalone/node_modules/

          mkdir deployment
          rsync -aL .next/standalone/ deployment/ || echo "Rsync: Some files could not be copied (likely broken symlinks)"
          cp -rL public deployment/public || true
          cp -rL .next/static deployment/.next/static || true

          cd deployment
          tar -czf ../release.tar.gz .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.8
        with:
          app-name: "cms"
          slot-name: "Production"
          package: release.tar.gz
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_10465936071D4A7AA627DEB04C65156B }}
